name: my_caliana_apps
description: "Technical test flutter apps"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.6.6
  carousel_slider: ^5.0.0
  flutter_keyboard_visibility: ^6.0.0
  animated_bottom_navigation_bar: ^1.3.3
  flutter_speed_dial: ^7.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/